Exec spPlancenterImportCenterAddSeparation3
@PageCountChanged=0
,@KeepColors=1
,@KeepApproval=1
,@KeepUnique=1
,@UseMainLocation=0
,@FirstPagePosition=0
,@CopyFlatSeparationSet=2882
,@NumberOfColors = 4
,@Copies = 1
,@PublicationID = 11
,@SectionID = 4
,@EditionID = 3
,@IssueID  = 1
,@PubDate = :pubdate
,@PageName = '8'
,@ColorID = 4
,@TemplateID = 3
,@ProofID = 2
,@DeviceID = 0
,@Version = 1
,@Pagination = 8
,@Approval = -1
,@Hold = 1
,@Active = 1
,@Priority = 100
,@PagePositions = '4'
,@PageType = 0
,@PagesOnPlate = 4
,@SheetNumber = 4
,@SheetSide = 1
,@PressId = 1
,@PressSectionNumber = 2
,@SortingPosition = ''
,@PressTower = ''
,@PressZone = ''
,@PressCylinder = ''
,@PressHighlow = ''
,@ProductionID = 12
,@PressrunID = 89
,@PlanPageName = ''
,@IssueSequenceNumber = 1
,@UniquePage = 1
,@LocationID = 1
,@FlatProofID = 0
,@Creep = :creep
,@MarkGroups = ''
,@PageIndex = 8
,@HardProofID = 0
,@DeadLine = :DeadLine
,@Comment = ''
,@MasterEditionID = 1
,@MasterLocationID = 1
,@ColorIndex  = 4
,@CustomerID  = 0
,@CopiesToProduce= 1
,@Miscint1= 0
,@Miscint2= 0
,@Miscint3= 161753143
,@Miscint4= 0
,@Miscstring1= '02'
,@Miscstring2= ''
,@Miscstring3= '20141011074110395'
,@Miscdate= :miscdate
,@PageFormatID= 6
,@RipSetupID= 131585
